heavy = {'slashing':0.5, 'piercing':1, 'blunt':2}
light = {'slashing':2, 'piercing':1, 'blunt':0.5}
player_stats = {'health':100, 'strength':1, 'agility':1, 'endurance':50, 'health_max':100, 'endurance_max':50, 'name':'none'}
player_equipment = {}
galen_stats = {'health':100, 'strength':1, 'agility':1, 'endurance':50, 'health_max':100, 'endurance_max':50, 'name':'Galen'}
galen_equipment = {'armour':light, 'damage_type':'slashing', 'handle_type':'onehanded', 'weapon_name':'sword', 'armour_type':'light armour'}
mercer_stats = {'health':150, 'strength':4, 'agility':4, 'endurance':70, 'health_max':150, 'endurance_max':70, 'name':'Mercer'}
mercer_equipment = {'armour':heavy, 'damage_type':'slashing', 'handle_type':'twohanded', 'weapon_name':'haliberd', 'armour_type':'heavy armour'}
crixus_stats = {'health':200, 'strength':7, 'agility':7, 'endurance':85, 'health_max':200, 'endurance_max':85, 'name':'Crixus'}
crixus_equipment = {'armour':heavy, 'damage_type':'piercing', 'handle_type':'onehanded', 'weapon_name':'light spear', 'armour_type':'heavy armour'}
armipotens_stats = {'health':250, 'strength':10, 'agility':10, 'endurance':100, 'health_max':250, 'endurance_max':100, 'name':'Arminpotens'}
armipotens_equipment = {'armour':light, 'damage_type':'blunt', 'handle_type':'twohanded', 'weapon_name':'warhammer', 'armour_type':'light armour'}
ulfric_stats = {'health':500, 'strength':15, 'agility':15, 'endurance':150, 'health_max':500, 'endurance_max':150, 'name':'Ulfric'}
ulfric_equipment = {'armour':heavy, 'damage_type':'piercing', 'handle_type':'twohanded', 'weapon_name':'infantry pike', 'armour_type':'heavy armour'}
stats = [galen_stats, mercer_stats, crixus_stats, armipotens_stats, ulfric_stats]
equipment = [galen_equipment, mercer_equipment, crixus_equipment, armipotens_equipment, ulfric_equipment]